title: EEP
description: English Etymology Project
author: Pierre ML


baseurl: /GHpages
url: https://nevaada.github.io


kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
    
 exclude: ["Readme.md"]